apiVersion: v1
kind: Service
metadata:
  name: wordsearch-service
spec:
  selector:
    app: wordsearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # or NodePort if you are running Kubernetes locally
